name: 'GitHub Actions CuiCui Bot'

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cuicui:
    env:
      WX_PUSHER_TOKEN: ${{ secrets.WX_PUSHER_TOKEN }}
      WX_UID: ${{ secrets.WX_UID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Install node'
        uses: actions/setup-node@v1
      - name: 'Run code'
        run: node main.js
        env:
          WX_PUSHER_TOKEN: ${{ secrets.WX_PUSHER_TOKEN }}
          WX_UID: ${{ secrets.WX_UID }}
          UP_ID: ${{ secrets.UP_ID }}
